server:
  port: 9002

spring:
  application:
    name: ADS-SERVICE

eureka:
  client:
    service-url.def ault: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}