server:
  port: 9000

spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    service-url.def ault: http://localhost:8761/eureka
    instance:
      hostname: localhost
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

