server:
  port: 80

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: CHAT-SERVICE
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/messanger/

eureka:
  client:
    service-url.def ault: http://localhost:8761/eureka
  instance:
    hostname: localhost

# old gateway configuration

#zuul:
#  ribbon:
#    eager-load:
#      enabled: true
#  routes:
#    user-service:
#      path: /user/**
#      service-id: USER-SERVICE
#    chat-service:
#      path: /messenger/**
#      service-id: CHAT-SERVICE
#  ignored-patterns: /**
