<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Confirm mail</title>
</head>
<body>
    <div class="message-wrapper">
        <h2>Please click following button to confirm your email</h2>
        <a href="http://127.0.0.1:80/user/confirm-mail/${confirm_code}">confirm</a>
    </div>
</body>
</html>